//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNV_CHBHXM.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CongViec
    {
        public int MaCV { get; set; }
        public string MaNV { get; set; }
        public System.DateTime NgayLam { get; set; }
        public Nullable<decimal> TongTien { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
