//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNV_CHBHXM.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Luong
    {
        public string MaNV { get; set; }
        public int Thang { get; set; }
        public int Nam { get; set; }
        public int SoNgayThucLam { get; set; }
        public Nullable<decimal> TongDoanhThu { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
