//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNV_CHBHXM.DTO
{
    using System;
    
    public partial class USP_TimKiemVaSapXepChiTietCV_Result1
    {
        public Nullable<int> MaDG { get; set; }
        public string TenDV { get; set; }
        public string TenLX { get; set; }
        public Nullable<int> DonGia { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> Tong { get; set; }
    }
}
